### ISSUE TITLE
No license added

### ISSUE THREAD

**Issue by arnevermeulen** [kweaver00/eliza#2]
Hi,
For a school project I have to create an implementation of eliza. I used your code to understand the principle behind it and then wrote everything according to my own interpretation. Now, it would be useful to reuse the default responses and synonyms you created (If you're okay with this). However, I am only allowed to use things of which I can mention the license and I can't really find it on this page. (I'm new to this stuff, so maybe I missed it.)

Thanks already for the explanation of eliza!

**Comment by keithweaver** [comment]
Feel free to use it. I'll add an MIT licence.

**Comment by keithweaver** [comment]
Added, closing
